package no.ntnu.genre;

import org.springframework.data.repository.CrudRepository;

/**
 * Repository interface for Genres, methods auto-generated by Spring Boot. SQL Database access.
 */
public interface GenreRepository extends CrudRepository<Genre, Integer> {
}
